#!/bin/bash

clang-format -n -Werror --ferror-limit=9999 $(git diff --cached --name-only)

for FILE in $(git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp|java)$' )
do
  clang-format -n -Werror -ferror-limit=99999 $FILE
done
